### ISSUE TITLE
problem getting the correct credentials "Flutter Navigator"

### ISSUE THREAD

**Issue by sandmen** [heremaps/here-sdk-ref-app-flutter#44]
Got the app compiled and running on Android,
but when I enter my Key_Id and Secret_Key generated by here-platform access manager OAuth2.0, I get "Download Metadata failed: These credentials do not authorize access".

Routing and searching for locations are working, but no maps !

My question is, how and where do I generate the right credentials for the flutter navigator edition ?
Is the developer or the platform the right place ?
By the way, I tried both.

**Comment by stefan-troyke** [comment]
Hi,

since we should not share the key ids here, I would recommend to go back to your assigned sales representative or account manager. It seems you don't have properly enabled platform credentials for the HERE SDK Navigate Edition for Flutter. developer.here.com is not the right place to get these credentials but your assigned representative should be able to help you. I hope this helps.

**Comment by sandmen** [comment]
Hi,
of course, didn't though to put my key's here in my question.
I have already contacted my sales representativ... I will see.
Maybe I'm not complete wrong, because postman is doing a good job with my credentials.
